### ISSUE TITLE
ZDF ApiToken changed 

### ISSUE THREAD

**Issue by ghost** [generia/plugin.video.zdf_de_2016#10]
Hello,
i noticed that since Thursday 5.11.17 the ZDF Mediathek Addon did not work anymore.

Solution: Change the API Token. 

New ApiToken is   69c4eddbe0cf82b2a9277e8106a711db314a3008

LibreELEC:~/.kodi/addons/plugin.video.zdf_de_2016/de/generia/kodi/plugin/frontend/zdf/Constants.py 

apiToken = '69c4eddbe0cf82b2a9277e8106a711db314a3008'

**Comment by generia** [comment]
Hi, 
thanks for the notification. There is a fix for this in next version 1.0.6. See also pull request https://github.com/xbmc/repo-plugins/pull/1447
