### ISSUE TITLE
Why is this plugin only available for xbmc:jarvis but not for xbmc:krypton?

### ISSUE THREAD

**Issue by jamtwister** [generia/plugin.video.zdf_de_2016#12]

**Comment by jamtwister** [comment]
Sorry it is a bit confusing for me. I am using the latest OSMC with kodi 17.4 -> krypton.

I would like to upgrade your plugin to 1.0.6, but that is not possible.
Normally it should be there, this mirror shows version 1.0.6 -> http://mirrors.kodi.tv/addons/krypton/plugin.video.zdf_de_2016/
But it is always version 1.0.5

**Comment by generia** [comment]
Hi jamtwister,
thanks for asking. I think this is a timing issue. 
Martijn merged the changes for 1.0.6 yesterday (https://github.com/xbmc/repo-plugins/pull/1447).
I suppose there are some automated copy jobs to update the related mirror servers. Maybe this takes some hour.

If I get you right, you can not see 1.0.6 in your OSMC Kodi GUI, but you can see it on the mirror.
I just tried this with my Kodi 17.3 on my notebook and I also don't see a newer version.

To be honest, I'm a bit clueless here.
But as a last resort you can download the zip from the mirror and install it manually via "Install from zip file" in your OSMC.

Best.
