### ISSUE TITLE
failure calling self._parseModule

### ISSUE THREAD

**Issue by jamtwister** [generia/plugin.video.zdf_de_2016#13]
class VideoResource and class RubricResource have the _parseModule method.
But their signature are different. The error occurs when instance of VideoResource calls parse method of RubicResource. At this call the _parseModule method of VideoResource is use, but the one of RubicResource is expected.

More details at log file.

PS: How do you test/debug your code? Have you installed kodi on your PC? If there is any easy way to debug please tell me.

[error.log](https://github.com/generia/plugin.video.zdf_de_2016/files/1439035/error.log)

**Comment by generia** [comment]
Thanks for the info. Seems that this slipped through. 
Can you give me the zdf-url that caused the issue? Should right before the exception stack trace in the logs.

PS: I'm using Eclipse with the Python tooling. Testing very "handson" using https://github.com/generia/plugin.video.zdf_de_2016/blob/master/test_zdf_search.py for the parsing that is idependent of Kodi.
For the frontend testing I linked the addon folder in Kodi to the files in the Eclipse workspace.

**Comment by generia** [comment]
Found it. This happens only, if there is no api-token in the token-cache. That's why I did not get the issue on my system. Fix is commited.
