### ISSUE TITLE
Low resolution on Kodi Version newer than 17.6

### ISSUE THREAD

**Issue by cabriofahrer** [generia/plugin.video.zdf_de_2016#17]
The plugin "ZDF Mediathek 2016" works fine with high resolution in Kodi up to version 17.6. On newer versions, like 18.6 you only get a resulution of 480x272 pixels.

**Comment by generia** [comment]
Thanks for the info, will take a look into this.

**Comment by generia** [comment]
So, it took a while, but the fix is done. Pull request is merged https://github.com/xbmc/repo-plugins/pull/3274.
