### ISSUE TITLE
Does not seem to work right...

### ISSUE THREAD

**Issue by marcvs** [generia/plugin.video.zdf_de_2016#2]
I've got it sort of working. However, I can only play films that I browsed via the "categories" selection. I.e. searches yield no results, "meist-gesehen" is empty, ...
Is this intentional?

**Comment by generia** [comment]
seems that zdf updated their page. that's the joy of web-scraping. I will have a look at it ...

**Comment by generia** [comment]
fixed with new version 1.0.2

**Comment by generia** [comment]
created pull-request for new version for Jarvis repo: https://github.com/xbmc/repo-plugins/pull/923
