### ISSUE TITLE
please lower required XBMC version to 2.14.0

### ISSUE THREAD

**Issue by stsichler** [generia/plugin.video.zdf_de_2016#4]
Hi, 
as your plugin seems to run on XBMC Gotham without any flaws (which is important for me, because I cannot upgrade to Kodi), could you please lower required version in addon.xml to 2.14.0?
That would be great!
Thank you for your work.

**Comment by generia** [comment]
Hi, as followup to our discussion in https://github.com/generia/plugin.video.zdf_de_2016/issues/1. I lowered the required xbmc version. So the plugin can run on Gotham.
The pull request for the change is submitted, see https://github.com/xbmc/repo-plugins/pull/995.
