### ISSUE TITLE
Keine Videos aus Raspberry PI (OSMC oder Libreelec)

### ISSUE THREAD

**Issue by bornello** [generia/plugin.video.zdf_de_2016#6]
Hallo,
ich bin mir sicher, dass am Anfang des Jahres ich noch Videos, Wilsberg zum Beispiel, aufrufen konnte.
Doch nun funktioniert kein Video mehr. Habe OSMC und libreelec auf dem Raspberry Pi ausprobiert, beide haben den selben Fehler, dass der Stream nicht gelesen werden kann. Auf meinem Windows 10 funktioniert es einwandfrei,..wahrscheinlich also eher ein Problem mit dem Raspberry ?
Habe gerade kein LogFile, da mein PI gerade neu aufgesetzt wird...das OSMC update hat mein NOOBS zerschossen....sobald ich ein Logfile habe poste ich den Inhalt.

**Comment by bornello** [comment]
ok...das neueste Update von OSMC hat gerade das Problem behoben.

**Comment by bornello** [comment]
Hallo,
zu frueh gefreut :)
Eine Sendung hat funktioniert, Heute vom aktuellen Tag, Wilsberg oder etwas anderes funktioniert nicht.
Habe es mittlerweile auch mit einer alten 15.2 Version von Kodi probiert, immer noch das Problem.
Logfile : (OSMC Kodi17.3)
21:29:04.551 T:3025625088  NOTICE: VideoPlayer: Opening: https://zdfvodnone-vh.akamaihd.net/i/meta-files/zdf/smil/m3u8/300/16/06/160626_wilsberg_ps_wil/3/160626_wilsberg_ps_wil.smil/master.m3u8
21:29:04.552 T:3025625088 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
21:29:05.329 T:2567959536  NOTICE: Creating InputStream
21:29:06.019 T:2567959536  NOTICE: Creating Demuxer
21:29:36.506 T:2567959536   ERROR: OpenDemuxStream - Error creating demuxer
21:29:36.506 T:2567959536  NOTICE: CVideoPlayer::OnExit()
21:29:36.507 T:3025625088   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.zdf_de_2016/?pagelet=PlayVideo&genre=Filme+%7C+Wilsberg&contentName=wilsberg-die-bielefeld-verschwoerung-102&title=%28%3E%29+Wilsberg+-+Die+Bielefeld-Verschw%C3%B6rung&apiToken=d2726b6c8c655e42b68b0db26131b15b22bd1a32]
21:29:36.578 T:3025625088  NOTICE: CVideoPlayer::CloseFile()
21:29:36.578 T:3025625088  NOTICE: VideoPlayer: waiting for threads to exit
21:29:36.578 T:3025625088  NOTICE: VideoPlayer: finished waiting
21:29:36.582 T:3025625088  NOTICE: CVideoPlayer::CloseFile()
21:29:36.582 T:3025625088  NOTICE: VideoPlayer: waiting for threads to exit
21:29:36.582 T:3025625088  NOTICE: VideoPlayer: finished waiting

**Comment by generia** [comment]
Danke für die Info. Ich werde mir das mal ansehen.

**Comment by bornello** [comment]
Hallo,
danke.Sieht fast so aus als waere das Problem das folgende:
auf den OSs auf denen ich das probiert have ist ffmpeg scheinbar nicht mit SSL kompiliert. Zumindestens sagt ffmpeg -protocols nicht, dass es HTTPS versteht ;)
Ich setze gerade ein qemu mit rasbian auf um der Spur nachzugehen. Halte dich auf dem laufenden.

**Comment by generia** [comment]
Ok, das deckt sich mit meinen Beobachtungen. Ich habe es mit verschiedenen Kodi-Versionen (16, 17) auf Mac und Pi versucht. Das klappt soweit. Tatsächlich ist es so, dass in diesem Fall sich der Kodi Player beschwert. Das ZDF Mediathek 2016 Plugin ist zu dem Zeitpunkt schon fertig. Es sucht nur die Video-URL von der ZDF Website und übergibt sie an den Player. Den Rest mach Kodi selbst.

Ich habe ein ähnliches Problem mit HTTPS Streams auf meinem Mac mit XBMC Gotham (13.x). Vielleicht helfen die Links in Issue #1 Dir hier weiter.

Zu Testen ob es einen Zusammenhang mit dem ZDF Mediathek 2016 Plugin gibt, könntest Du das Video auch mal über die folgende Playlist mit dem Simple IPTV Plugin laden.

```
#EXTM3U
#EXTINF:0,ZDF Mediathek 2016 - Wilsberg Test
https://zdfvodnone-vh.akamaihd.net/i/meta-files/zdf/smil/m3u8/300/16/06/160626_wilsberg_ps_wil/3/160626_wilsberg_ps_wil.smil/master.m3u8

```

**Comment by generia** [comment]
Das Problem liegt wahrscheinlich außerhalb des Plugins.
Sollte das nicht der Fall sein, bitte diesen Issue wieder öffnen.
