### ISSUE TITLE
RubricPage von Bares für Rares führt zu PythonToCppException

### ISSUE THREAD

**Issue by Itja** [generia/plugin.video.zdf_de_2016#7]
Hallo generia, erstmal vielen Dank für dein Plugin! [Diese Exception](https://github.com/generia/plugin.video.zdf_de_2016/files/1099222/zdf-bfr-crashlog.txt) wird derzeit (auch mit dem aktuellen master ausprobiert) geworfen, während versucht wird auf der RubricPage von o.g. Sendung das Teaserbild zu laden.

Als Workaround reicht es, die Zeilen 60 und 61 in der `RubricPage.py` auszukommentieren:

    def _checkTeasers(self, teasers, apiToken):
        for teaser in teasers:
            if teaser.image is None and teaser.contentName is not None:
                videoContentUrl = Constants.apiBaseUrl + '/content/documents/' + teaser.contentName + '.json?profile=player'
                self.debug("downloading video-content-url '{1}' ...", videoContentUrl)
                videoContent = VideoContentResource(videoContentUrl, Constants.apiBaseUrl, apiToken)
                #self._parse(videoContent)
                #teaser.image = videoContent.image

Wenn du keine Zeit haben solltest kann ich mich die Tage mal an einem Fix probieren.
Viele Grüße!

**Comment by generia** [comment]
Hi Itja, vielen Danke für die Info.
Das Problem sollte gefixt sein (siehe f2d08f0).
Die Bares für Rares Sendung vom kommenden Sonntag hat offenbar noch keine video-stream-url. Und der Parser war da noch etwas optimistisch, was die Datenlage angeht.
