### ISSUE TITLE
Plugin startet nicht mehr

### ISSUE THREAD

**Issue by stsichler** [generia/plugin.video.zdf_de_2016#8]
seit kurzem startet das Plugin nicht mehr. hat ZDF wiedermal etwas veraendert?

Folgende Fehlermeldung steht im Logfile:

21:29:50 T:2965398560  NOTICE: ZDF Mediathek 2016 [2]: [Plugin] - Python-Version: /usr/bin/python 2.7.6 (default, Oct 26 2016, 20:55:19) 
                                            [GCC 4.8.4]
21:29:50 T:2965398560  NOTICE: ZDF Mediathek 2016 [2]: [Plugin] - executing url=plugin://plugin.video.zdf_de_2016/ ...
21:29:50 T:2965398560  NOTICE: ZDF Mediathek 2016 [2]: [Mediathek] - Timer - parsing url='https://www.zdf.de/ZDFplayer/configs/zdf/zdf2016/configuration.json'
 ...
21:29:50 T:2965398560  NOTICE: ZDF Mediathek 2016 [2]: [ConfigurationResource] - Timer - loading url='https://www.zdf.de/ZDFplayer/configs/zdf/zdf2016/configu
ration.json' ...
21:29:50 T:2965398560  NOTICE: ZDF Mediathek 2016 [2]: [ConfigurationResource] - Timer - loading url='https://www.zdf.de/ZDFplayer/configs/zdf/zdf2016/configu
ration.json' ... done. [76 ms]
21:29:50 T:2965398560   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: ('apiToken',)
                                            Traceback (most recent call last):
                                              File "/home/odroid/.kodi/addons/plugin.video.zdf_de_2016-master/addon.py", line 169, in <module>
                                                pagelet.service(request, response)
                                              File "/home/odroid/.kodi/addons/plugin.video.zdf_de_2016-master/de/generia/kodi/plugin/frontend/zdf/Mediathek.py", line 13, in service
                                                self._parse(configuration)
                                              File "/home/odroid/.kodi/addons/plugin.video.zdf_de_2016-master/de/generia/kodi/plugin/frontend/base/Pagelet.py", line 122, in _parse
                                                resource.parse()
                                              File "/home/odroid/.kodi/addons/plugin.video.zdf_de_2016-master/de/generia/kodi/plugin/backend/zdf/ConfigurationResource.py", line 12, in parse
                                                self.apiToken = self.content['apiToken']
                                            KeyError: ('apiToken',)
                                            -->End of Python script error report<--

**Comment by generia** [comment]
Danke für die Info. Gestern abend ging es noch. Heute morgen scheint es nicht mehr zu tun. Ich schau rein ...

**Comment by generia** [comment]
zdf.de hat das apiToken Handling geändert. Fix ist eingecheckt. Pull-Request für Kodi Repo ist pending: https://github.com/xbmc/repo-plugins/pull/1347

**Comment by stsichler** [comment]
DANKE!
