### ISSUE TITLE
Untertitel abschalten

### ISSUE THREAD

**Issue by HeinerM** [generia/plugin.video.zdf_de_2016#9]
Sorry, dies ist sicher nicht der richtige Ort für meine Frage, aber ich konnte keine andere Anlaufstelle finden:
Seit Version 1.03 werden IMMER Untertitel in den Videos angezeigt, sofern eine entsprechende Version in der Mediathek verfügbar ist. Ich finde das sehr störend. Lässt sich das irgendwo abschalten?

**Comment by generia** [comment]
Die Untertitel kamen auf besonderen Wunsch in https://github.com/generia/plugin.video.zdf_de_2016/issues/3 dazu. Es ist tatsächlich etwas unübersichtlich in Kodi, wie man Untertitel dauerhaft ein und ausschaltet.

Der Trick ist bei laufender Wiedergabe im Menü "Einstellungen > Audio- und Untertitel-Einstellungen" die Untertitel zu aktivieren/deaktivieren. Dann bleibt die Einstellung dauerhaft erhalten. Eine Umstellung im "Untertitel" Menü gilt immer nur für die aktuelle Wiedergabe.

Sie dazu z.B. auch https://www.kodinerds.net/index.php/Thread/54599-Untertitel-deaktivieren/.

**Comment by HeinerM** [comment]
Vielen Dank für die schnelle Hilfe - und natürlich auch für das Addon, das ich gerne und oft nutze.
Heiner

Am 30. Juli 2017 23:30:24 MESZ schrieb generia <notifications@github.com>:
>Die Untertitel kamen auf besonderen Wunsch in
>https://github.com/generia/plugin.video.zdf_de_2016/issues/3 dazu. Es
>ist tatsächlich etwas unübersichtlich in Kodi, wie man Untertitel
>dauerhaft ein und ausschaltet.
>
>Der Trick ist bei laufender Wiedergabe im Menü "Einstellungen > Audio-
>und Untertitel-Einstellungen" die Untertitel zu
>aktivieren/deaktivieren. Dann bleibt die Einstellung dauerhaft
>erhalten. Eine Umstellung im "Untertitel" Menü gilt immer nur für die
>aktuelle Wiedergabe.
>
>Sie dazu z.B. auch
>https://www.kodinerds.net/index.php/Thread/54599-Untertitel-deaktivieren/.
>
>
>
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/generia/plugin.video.zdf_de_2016/issues/9#issuecomment-318931092

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.
